Java menu, Add mobile-menu using JavaScript.
TaiwoEnoch/Enoch-Portfolio pull request #12
Opened 2023-01-30 23:07 UTC by TaiwoEnoch

Add JavaScript functions to make my mobile menu responsive, I do not do it alone, I will like to acknowledge @MuhammadUsmanAslam my coding partner, for the collaboration.

2023-01-30 23:13 UTC, huseyinbiyik commented
Hi @TaiwoEnoch and @MuhammadUsmanAslam,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

⚠️ You have submitted a project, that has no Stylint checks pass. Kindly fix your linter errors before submitting for review. 
<img width="817" alt="Screenshot 2023-01-31 at 2 13 04 AM" src="https://user-images.githubusercontent.com/25887253/215617755-8e0cbb6c-e790-4fae-ab42-bee06590e7a5.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-30 23:18 UTC, TaiwoEnoch commented
Oh, i will work on it now

2023-01-30 23:26 UTC, TaiwoEnoch commented
Have make some corrections now, it is very okay now @huseyinbiyik

2023-01-31 00:11 UTC, osamaashraf6 requested changes
Hi @TaiwoEnoch 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Good commit messages.
- [x] Descriptive READme file in a professional way.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow
- [x] Nice design.




## Required Changes ♻️

- [ ] check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-31 00:11 UTC, osamaashraf6 commented on index.html
> +        </ul>
- [ ] Kindly 😃try to decrease the margin between elements to stick to the Figma Design and with that the mobile menu will be attractive for the visitors and clients who will communicate with you 😊
- [ ] Also consider adding the color of the nav links of the mobile menu like the color of the Figma Design 💯

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/215622903-04ec514c-a317-426d-914b-6a0395968adc.png)|   ![image](https://user-images.githubusercontent.com/83360636/215622928-38cd2e7b-c5d6-4337-bb00-5f56987c62ff.png) |

2023-01-31 00:11 UTC, osamaashraf6 commented on index.html
> +        <i id="mobile-menu-icon" class="fa-solid fa-x flex-end"></i>
- [ ] Good job at implementing the functionality of closing the mobile menu, but Kindly 😊try to add the correct color of the ```X ``` icon to be like the Figma Design 😃
- [ ] Also consider😃 decreasing the margin between the ```X``` icon and the nav links to be like the Figma Design👌

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/215624576-98c2b9e9-700f-40db-9276-30b31451e8df.png)|   ![image](https://user-images.githubusercontent.com/83360636/215624811-0e23567a-62bf-4594-8a07-48c147c4290a.png)|

2023-01-31 08:10 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Mobile menu working as expected :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 14:54 UTC, merged