Details popup
TaiwoEnoch/Enoch-Portfolio pull request #14
Opened 2023-02-02 13:43 UTC by TaiwoEnoch

I create this PR to feature
- JavaScript file for details popup
- Add some style using style.css file
- Make it more responsive dynamical and interactive for user, I acknowledge @MuhammadUsmanAslam my coding partner he did a great job in the cause of collaboration.

2023-02-02 13:46 UTC, levy002 reviewed
## Hello @TaiwoEnoch 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that fails linters. Kindly solve linter errors and submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-02 13:58 UTC, TaiwoEnoch commented
Oh, Thank you

2023-02-02 17:01 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @TaiwoEnoch , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 17:01 UTC, bobb-Rob commented on main.js
> +recent.appendChild(detailPopuop);
Well done on this project so far. I must commend your tenacious effort. I am here to help you get even better at what you are doing. I have a few suggestions and it will do you good to implement them. 

- [ ] I presume this is the pop-up for the first project i.e the **_featured_**. Your naming convention is somewhat misleading. it is a popular saying **_"Knowing the right name to call your variables, continues to be a huge challenge with software development."_** I and I agree. With more practice, you will get used to the right names. 
- [ ] Looking at the Figma design, you will see that the popup is the same for all cards, which means, you need only one popup component. It is best practice to not repeat yourself (DRY), if you really do not have to. I suggest you use the same popup for all project cards.

2023-02-02 17:01 UTC, bobb-Rob commented on main.js
> +});
- There are a couple of ways you can improve this code. Currently, the problem I see is that you are loading all project popups at page load. It means that if you have 100 projects, it loads all 100 projects  _**HTML elements and values**_ in the background, thereby littering the DOM tree. 

- To improve this code, we take advantage of `AddEventListener` method to dynamically add _**click**_ event  to the `see project`  button when clicked. See the code below: 

```javascript
const createPopUpComponent = (project) => {
  const laguages = project.projectLang.map((lang) => `<li class='code-list'>${lang}</li>`).join('');
  const detailPopuop = document.createElement('section');
  detailPopuop.classList.add('full-details');
  detailPopuop.id = `card-details-${index + 1}`;
  detailPopuop.innerHTML = `<div class='combination'>
  <div class='div-for-details d-flex'>
    <div class='main-heading-detailed d-flex'>
        <p class='heading-data'>${project.projectName}</p>
        <p class='heading-desktop-data-popup'>${project.projectName}</p>
        <nav class='switch-off'></nav>
          <i id='detail-card-off-${index + 1}' class='fa-solid fa-x details-menu'></i>
        </nav>
    </div>
    <ul class='new-list d-flex'>
      ${laguages}
    </ul>
    <div class='everything-details'>
      <div class='mobile-snap-popup'>
        <div class='snapshot-image flex-one'>
          <img class='deatails-popup-img' src='${project.featureImg}' class='snap-shot'>
        </div>
        <div class='deatail-words flex-one'>
          <p class='paragraph-desktop-popup'>${project.projectDescription}</p>
          <div class='div-for-button d-flex'>
            <a href='${project.seeLive}' class='details-button'>
              See Live
              <img src='./images/see-live.png'>
            </a>
            <a href='${project.seeSource}' class='details-button-btn'>
              See Source
              <img src='./images/src-gitHub.png'>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>`;
  return detailPopuop;
}

const displayPopUp = (project) => {
  const body = document.querySelector('body');
  const popup = createPopUpComponent();
  body.appendChild(popup);
}

const seeProjectButtonsNodeList = document.querySelectorAll('.see-project-btn'); //This return a Nodelist(array-like) list of all see-project buttons
const seeProjectButtons = Array(seeProjectButtonsNodeList); //This return an actual itterable array of see-project buttons.

// iterate through the button and add the even to display a popup
seeProjectButtons.forEach((button) => {
  button.addEventListener("click", (e) => {
    // using the e.target, you find out which project button was clicked,
    // first, you must have given each project a unique id in the static array.
    // You must have already given this button an id that is same with the one in each project array. 
    const projectId = e.target.id; //this is now project id becasue you passed it to the buttons.

    const currentProject = projects.find((project) => project.id === projectId);// FInd currently clicked project in the project array.
    displayPopUp(currentProject);
  })
})

```


Also, I think that you don't have to load this data on page-load, instead, you can put this popup into a function that will be called any time the `see project` button is clicked.

2023-02-02 17:01 UTC, bobb-Rob commented on main.js
> +});
- [ ] When you dynamically add the event as suggested above, you will not need all this code again. This is not a DRY code. Best of luck.

2023-02-02 17:01 UTC, bobb-Rob commented on styles.css
> +  transition-duration: 1s;
- [ ] Please ensure you follow the Figma design as much as possible. 

Figma Design | Your Project
--- | ---
![image](https://user-images.githubusercontent.com/84156714/216391833-3034c71c-e584-4797-a216-6c299c72366e.png) | ![image](https://user-images.githubusercontent.com/84156714/216391602-b6b24dcc-d2e9-49d9-84ff-8477b995d6f5.png) 


As you can see, there is a big difference.

2023-02-03 12:14 UTC, frank1738 approved these changes
Hi @TaiwoEnoch , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 13:13 UTC, merged